# Generated by Django 2.2.7 on 2019-12-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('date', models.DateField()),
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
