# Generated by Django 2.2.7 on 2019-12-13 15:20
import json
import os

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_statistics', '0001_initial'),
    ]

    operations = [
    ]
