# Generated by Django 2.2.7 on 2019-12-16 12:41
import json
import os

from django.db import migrations

def add_events(apps, schema_editor):
    Event = apps.get_model('run_statistics', 'Event')
    data_dir = os.path.abspath("run_statistics/data")
    json_files = os.listdir(data_dir)
    for file in json_files:
        path = os.path.join(data_dir, file)
        with open(path, 'r') as rf:
            data = json.load(rf)

        date = data['date']
        number = data['number']
        location = data['location']
        Event.objects.get_or_create(date=date, number=number, location=location)

class Migration(migrations.Migration):

    dependencies = [
        ('run_statistics', '0002_auto_20191213_1620'),
    ]

    operations = [
        migrations.RunPython(add_events),
    ]
