# Generated by Django 2.2.7 on 2019-12-13 15:18

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
