# Generated by Django 2.2.7 on 2019-12-16 13:20
import json
import os
import time

from django.db import migrations

def add_events(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    data_dir = os.path.abspath("users/data")
    json_files = os.listdir(data_dir)
    for file in json_files:
        path = os.path.join(data_dir, file)
        with open(path, 'r') as rf:
            data = json.load(rf)
        # # #
        # A version where there was an error with encoding (some files were not utf-8 encoded, produced errors
        # The enforcement of encoding was due to some cyrillic letters
        # try:
        #     with open(path, 'r') as rf:
        #         data = json.load(rf)
        #         print(f'LOAD:    ')
        # except UnicodeDecodeError as e:
            # with open(path, 'r', encoding='utf-8') as rf:
            #     data_string = rf.read()
            #     print(f'{data_string[e.start-1]}{data_string[e.start]}{data_string[e.start+1]}')
            #     data = json.loads(data_string, encoding='utf-8')

        for person in data:
            # print(f'file: {path}, person: {person}')
            Profile.objects.get_or_create(name=person['name'], gender=person['gender'], club=person['club'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191213_1618'),
    ]

    operations = [
        migrations.RunPython(add_events),
    ]
