# Generated by Django 2.2.7 on 2019-12-16 17:28
import json
import os

from django.db import migrations

def add_events(apps, schema_editor):
    Result = apps.get_model('base', 'Result')
    Profile = apps.get_model('users', 'Profile')
    Event = apps.get_model('run_statistics', 'Event')
    data_dir = os.path.abspath("base/data")
    json_files = os.listdir(data_dir)
    for file in json_files:
        path = os.path.join(data_dir, file)
        with open(path, 'r') as rf:
            data = json.load(rf)

        for entry in data:
            event = Event.objects.get(number=entry['event'])
            person = Profile.objects.get(name=entry['person'], gender=entry['gender'], club=entry['club'])
            finished = entry['finished']
            time = entry['time']
            age_group = entry['age_group']
            age_percentage = entry['age_percentage']
            Result.objects.get_or_create(event=event, person=person, finished=finished, time=time, age_group=age_group, age_percentage=age_percentage)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_events),
    ]
